[pytest]
markers =
    accuracy_default: Tests using the default accuracy
    accuracy_tight: Tests using tight accuracy
    accuracy_ludicrous: Tests using ludicrous accuracy
    avdz: Tests using the aug-cc-pVDZ basis set
    avtz: Tests using the aug-cc-pVTZ basis set
    avqz: Tests using the aug-cc-pVQZ basis set
    dimer: Tests on dimer systems
    trimer: Tests on trimer systems
    slow: Tests considered slow (e.g. trimers, avqz basis, tight/ludicrous accuracy)
