# ---------------------------------------------------------
# Definition of paths for all compiled and preprocessed
# source code files used by the build script
# ---------------------------------------------------------
#
# The compilation process is carried out in parallel based on the following assumptions:
# 1. Files belonging to the same sublist do not depend on each other. The program
# will attempt to use the maximum amount of concurrent processes to compile the current batch
# of files in parallel.
# 2. Files belonging to the given list depend on all previous lists. If a file
# in n-th list is changed, all files in batches n+1, n+2, ... are recompiled.
#
# Lists of source code files are tagged, e.g., "DFT" or "CC". The tagging mechanism is needed
# to switch parts of the program on/off according to the flags set for the build script or
# apply group-sepecific compilation flags.
#
# The preprocessing list, PreprocessList, comprises files with annotated sections in the source code,
# employed, e.g., for automated commenting/uncommenting at build time. The automated commenting
# mechanism is needed to eliminate references to the parts of the program disabled at build time.
# The annotated code sections have the following format:
# 
# !@CC
# ... calls to subroutines for copuled clusters computations...
# !@END CC
#
# List of all modules available for compilation
#
AllModules = set(["DFT", "CC"])
#
# Minimum set of modules required for compilation
#
MinimumModules = set(["DFT"])
FileList = []
FileList += [("DFT", ["common/arithmetic.f90"])]
FileList += [("DFT", ["common/math_constants.f90"])]
FileList += [("DFT", ["common/string.f90",
                      "common/h_io.f90",
                      "common/h_voldata.f90",
                      "common/clock.f90",
                      "common/sort.f90",
                      "common/specf.f90",
                      "common/cg.f90",
                      "common/qnewton.f90",
                      "common/gaussquad.f90",
                      "integrals/grid/grid_definitions.f90",
                      "integrals/Cholesky/TwoStepCholesky_definitions.f90"])]
FileList += [("DFT", ["integrals/THC/thc_definitions.f90"])]
FileList += [("DFT", ["common/display.f90"])]
FileList += [("DFT", ["common/journal.f90"])]
FileList += [("DFT", ["common/h_xcfunc.f90"])]
FileList += [("DFT", ["scf/scf_definitions.f90",
                      "rpa/rpa_definitions.f90"])]
FileList += [("DFT", ["common/gparam.f90"])]
FileList += [("DFT", ["common/io.f90",
                      "common/periodic.f90",
                      "common/uniopt.f90"])]
FileList += [("DFT", ["common/sys_definitions.f90"])]
FileList += [("DFT", ["linear-algebra/blas1.f90",
                 "linear-algebra/blas2.f90",
                 "linear-algebra/blas3.f90",
                 "linear-algebra/blas4.f90",
                 "linear-algebra/cmplx_linalg.f90",
                 "linear-algebra/linalg.f90",
                 "linear-algebra/matexp.f90",
                 "linear-algebra/real_linalg.f90"])]
FileList += [("DFT", ["linear-algebra/blas5.f90",
                 "linear-algebra/blas6.f90"])]
FileList += [("DFT", ["linear-algebra/blas_olenkifer.f90"])]

FileList += [("DFT", ["integrals/chebinterp.f90",
                      "integrals/spherh.f90",
                      "integrals/hermite.f90",
                      "integrals/hermite_automatic.f90",
                      "integrals/ericonst.f90",
                      "integrals/lcexch.f90",
                      "integrals/grid/LebedevGrid.f90"])]
FileList += [("DFT", ["integrals/gto.f90",
                      "integrals/boys.f90"])]
FileList += [("DFT", ["integrals/ECP/ecpint.f90"])]
FileList += [("DFT", ["integrals/ECP/spin_orbit_ecp.f90"])]
FileList += [("DFT", ["integrals/ddds.f90",
                 "integrals/ddps.f90",
                 "integrals/ddss.f90",
                 "integrals/dpds.f90",
                 "integrals/dppp.f90",
                 "integrals/dpps.f90",
                 "integrals/dpss.f90",
                 "integrals/dsds.f90",
                 "integrals/dspp.f90",
                 "integrals/dsps.f90",
                 "integrals/dsss.f90",
                 "integrals/fdss.f90",
                 "integrals/fpps.f90",
                 "integrals/fpss.f90",
                 "integrals/fsds.f90",
                 "integrals/fspp.f90",
                 "integrals/fsps.f90",
                 "integrals/fsss.f90",
                 "integrals/llll.f90",
                 "integrals/llpp.f90",
                 "integrals/llsp.f90",
                 "integrals/llss.f90",
                 "integrals/pppp.f90",
                 "integrals/ppsp.f90",
                 "integrals/ppss.f90",
                 "integrals/spsp.f90",
                 "integrals/spss.f90",
                 "integrals/ssss.f90",
                 "integrals/multipole.f90",
                 "integrals/nuclfield.f90",
                 "integrals/lebedev.f90"])]
FileList += [("DFT", ["integrals/ints.f90",
                 "integrals/grid.f90"])]
# ------------------------------------------------------
# Automatically generated two-electron integrals
# ------------------------------------------------------
FileList += [("DFT", ["integrals/Auto2e/src/auto2e_BraTransform.f90", 
"integrals/Auto2e/src/auto2e_Hermite.f90", 
"integrals/Auto2e/src/auto2e_KetTransfer.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_10.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_5.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_6.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_7.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_8.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_10_9.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_2_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_2_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_3_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_3_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_3_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_4_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_4_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_4_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_4_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_5_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_5_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_5_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_5_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_5_5.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_5_part1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_5_part2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_6_part1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_6_part2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_6_6_part3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_5.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_6.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_7_7.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_5.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_6.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_7.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_8_8.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_1.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_2.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_3.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_4.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_5.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_6.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_7.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_8.f90", 
"integrals/Auto2e/src/auto2e_KetTransform_9_9.f90",
"integrals/Auto2e/src/auto2e_SpherTransf.f90"])]
FileList += [("DFT", ["integrals/Auto2e/src/auto2e_WMatrix_part1.f90", 
"integrals/Auto2e/src/auto2e_WMatrix_part2.f90", 
"integrals/Auto2e/src/auto2e_WMatrix_part3.f90"])]
FileList += [("DFT", ["integrals/Auto2e/src/auto2e_eri_dddd.f90", 
"integrals/Auto2e/src/auto2e_eri_dddp.f90", 
"integrals/Auto2e/src/auto2e_eri_ddds.f90", 
"integrals/Auto2e/src/auto2e_eri_ddpp.f90", 
"integrals/Auto2e/src/auto2e_eri_ddps.f90", 
"integrals/Auto2e/src/auto2e_eri_ddss.f90", 
"integrals/Auto2e/src/auto2e_eri_dpdp.f90", 
"integrals/Auto2e/src/auto2e_eri_dpds.f90", 
"integrals/Auto2e/src/auto2e_eri_dppp.f90", 
"integrals/Auto2e/src/auto2e_eri_dpps.f90", 
"integrals/Auto2e/src/auto2e_eri_dpss.f90", 
"integrals/Auto2e/src/auto2e_eri_dsds.f90", 
"integrals/Auto2e/src/auto2e_eri_dspp.f90", 
"integrals/Auto2e/src/auto2e_eri_dsps.f90", 
"integrals/Auto2e/src/auto2e_eri_dsss.f90", 
"integrals/Auto2e/src/auto2e_eri_fddd.f90", 
"integrals/Auto2e/src/auto2e_eri_fddp.f90", 
"integrals/Auto2e/src/auto2e_eri_fdds.f90", 
"integrals/Auto2e/src/auto2e_eri_fdfd.f90", 
"integrals/Auto2e/src/auto2e_eri_fdfp.f90", 
"integrals/Auto2e/src/auto2e_eri_fdfs.f90", 
"integrals/Auto2e/src/auto2e_eri_fdpp.f90", 
"integrals/Auto2e/src/auto2e_eri_fdps.f90", 
"integrals/Auto2e/src/auto2e_eri_fdss.f90", 
"integrals/Auto2e/src/auto2e_eri_ffdd.f90", 
"integrals/Auto2e/src/auto2e_eri_ffdp.f90", 
"integrals/Auto2e/src/auto2e_eri_ffds.f90", 
"integrals/Auto2e/src/auto2e_eri_fffd.f90", 
"integrals/Auto2e/src/auto2e_eri_ffff.f90", 
"integrals/Auto2e/src/auto2e_eri_fffp.f90", 
"integrals/Auto2e/src/auto2e_eri_fffs.f90", 
"integrals/Auto2e/src/auto2e_eri_ffpp.f90", 
"integrals/Auto2e/src/auto2e_eri_ffps.f90", 
"integrals/Auto2e/src/auto2e_eri_ffss.f90", 
"integrals/Auto2e/src/auto2e_eri_fpdd.f90", 
"integrals/Auto2e/src/auto2e_eri_fpdp.f90", 
"integrals/Auto2e/src/auto2e_eri_fpds.f90", 
"integrals/Auto2e/src/auto2e_eri_fpfp.f90", 
"integrals/Auto2e/src/auto2e_eri_fpfs.f90", 
"integrals/Auto2e/src/auto2e_eri_fppp.f90", 
"integrals/Auto2e/src/auto2e_eri_fpps.f90", 
"integrals/Auto2e/src/auto2e_eri_fpss.f90", 
"integrals/Auto2e/src/auto2e_eri_fsdd.f90", 
"integrals/Auto2e/src/auto2e_eri_fsdp.f90", 
"integrals/Auto2e/src/auto2e_eri_fsds.f90", 
"integrals/Auto2e/src/auto2e_eri_fsfs.f90", 
"integrals/Auto2e/src/auto2e_eri_fspp.f90", 
"integrals/Auto2e/src/auto2e_eri_fsps.f90", 
"integrals/Auto2e/src/auto2e_eri_fsss.f90", 
"integrals/Auto2e/src/auto2e_eri_gddd.f90", 
"integrals/Auto2e/src/auto2e_eri_gddp.f90", 
"integrals/Auto2e/src/auto2e_eri_gdds.f90", 
"integrals/Auto2e/src/auto2e_eri_gdfd.f90", 
"integrals/Auto2e/src/auto2e_eri_gdff.f90", 
"integrals/Auto2e/src/auto2e_eri_gdfp.f90", 
"integrals/Auto2e/src/auto2e_eri_gdfs.f90", 
"integrals/Auto2e/src/auto2e_eri_gdgd.f90", 
"integrals/Auto2e/src/auto2e_eri_gdgp.f90", 
"integrals/Auto2e/src/auto2e_eri_gdgs.f90", 
"integrals/Auto2e/src/auto2e_eri_gdpp.f90", 
"integrals/Auto2e/src/auto2e_eri_gdps.f90", 
"integrals/Auto2e/src/auto2e_eri_gdss.f90", 
"integrals/Auto2e/src/auto2e_eri_gfdd.f90", 
"integrals/Auto2e/src/auto2e_eri_gfdp.f90", 
"integrals/Auto2e/src/auto2e_eri_gfds.f90", 
"integrals/Auto2e/src/auto2e_eri_gffd.f90", 
"integrals/Auto2e/src/auto2e_eri_gfff.f90", 
"integrals/Auto2e/src/auto2e_eri_gffp.f90", 
"integrals/Auto2e/src/auto2e_eri_gffs.f90", 
"integrals/Auto2e/src/auto2e_eri_gfgd.f90", 
"integrals/Auto2e/src/auto2e_eri_gfgf.f90", 
"integrals/Auto2e/src/auto2e_eri_gfgp.f90", 
"integrals/Auto2e/src/auto2e_eri_gfgs.f90", 
"integrals/Auto2e/src/auto2e_eri_gfpp.f90", 
"integrals/Auto2e/src/auto2e_eri_gfps.f90", 
"integrals/Auto2e/src/auto2e_eri_gfss.f90", 
"integrals/Auto2e/src/auto2e_eri_ggdd.f90", 
"integrals/Auto2e/src/auto2e_eri_ggdp.f90", 
"integrals/Auto2e/src/auto2e_eri_ggds.f90", 
"integrals/Auto2e/src/auto2e_eri_ggfd.f90", 
"integrals/Auto2e/src/auto2e_eri_ggff.f90", 
"integrals/Auto2e/src/auto2e_eri_ggfp.f90", 
"integrals/Auto2e/src/auto2e_eri_ggfs.f90", 
"integrals/Auto2e/src/auto2e_eri_gggd.f90", 
"integrals/Auto2e/src/auto2e_eri_gggf.f90", 
"integrals/Auto2e/src/auto2e_eri_gggg.f90", 
"integrals/Auto2e/src/auto2e_eri_gggp.f90", 
"integrals/Auto2e/src/auto2e_eri_gggs.f90", 
"integrals/Auto2e/src/auto2e_eri_ggpp.f90", 
"integrals/Auto2e/src/auto2e_eri_ggps.f90", 
"integrals/Auto2e/src/auto2e_eri_ggss.f90", 
"integrals/Auto2e/src/auto2e_eri_gpdd.f90", 
"integrals/Auto2e/src/auto2e_eri_gpdp.f90", 
"integrals/Auto2e/src/auto2e_eri_gpds.f90", 
"integrals/Auto2e/src/auto2e_eri_gpfd.f90", 
"integrals/Auto2e/src/auto2e_eri_gpff.f90", 
"integrals/Auto2e/src/auto2e_eri_gpfp.f90", 
"integrals/Auto2e/src/auto2e_eri_gpfs.f90", 
"integrals/Auto2e/src/auto2e_eri_gpgp.f90", 
"integrals/Auto2e/src/auto2e_eri_gpgs.f90", 
"integrals/Auto2e/src/auto2e_eri_gppp.f90", 
"integrals/Auto2e/src/auto2e_eri_gpps.f90", 
"integrals/Auto2e/src/auto2e_eri_gpss.f90", 
"integrals/Auto2e/src/auto2e_eri_gsdd.f90", 
"integrals/Auto2e/src/auto2e_eri_gsdp.f90", 
"integrals/Auto2e/src/auto2e_eri_gsds.f90", 
"integrals/Auto2e/src/auto2e_eri_gsfd.f90", 
"integrals/Auto2e/src/auto2e_eri_gsff.f90", 
"integrals/Auto2e/src/auto2e_eri_gsfp.f90", 
"integrals/Auto2e/src/auto2e_eri_gsfs.f90", 
"integrals/Auto2e/src/auto2e_eri_gsgs.f90", 
"integrals/Auto2e/src/auto2e_eri_gspp.f90", 
"integrals/Auto2e/src/auto2e_eri_gsps.f90", 
"integrals/Auto2e/src/auto2e_eri_gsss.f90", 
"integrals/Auto2e/src/auto2e_eri_hddd.f90", 
"integrals/Auto2e/src/auto2e_eri_hddp.f90", 
"integrals/Auto2e/src/auto2e_eri_hdds.f90", 
"integrals/Auto2e/src/auto2e_eri_hdfd.f90", 
"integrals/Auto2e/src/auto2e_eri_hdff.f90", 
"integrals/Auto2e/src/auto2e_eri_hdfp.f90", 
"integrals/Auto2e/src/auto2e_eri_hdfs.f90", 
"integrals/Auto2e/src/auto2e_eri_hdgd.f90", 
"integrals/Auto2e/src/auto2e_eri_hdgf.f90", 
"integrals/Auto2e/src/auto2e_eri_hdgg.f90", 
"integrals/Auto2e/src/auto2e_eri_hdgp.f90", 
"integrals/Auto2e/src/auto2e_eri_hdgs.f90", 
"integrals/Auto2e/src/auto2e_eri_hdhd.f90", 
"integrals/Auto2e/src/auto2e_eri_hdhp.f90", 
"integrals/Auto2e/src/auto2e_eri_hdhs.f90", 
"integrals/Auto2e/src/auto2e_eri_hdpp.f90", 
"integrals/Auto2e/src/auto2e_eri_hdps.f90", 
"integrals/Auto2e/src/auto2e_eri_hdss.f90", 
"integrals/Auto2e/src/auto2e_eri_hfdd.f90", 
"integrals/Auto2e/src/auto2e_eri_hfdp.f90", 
"integrals/Auto2e/src/auto2e_eri_hfds.f90", 
"integrals/Auto2e/src/auto2e_eri_hffd.f90", 
"integrals/Auto2e/src/auto2e_eri_hfff.f90", 
"integrals/Auto2e/src/auto2e_eri_hffp.f90", 
"integrals/Auto2e/src/auto2e_eri_hffs.f90", 
"integrals/Auto2e/src/auto2e_eri_hfgd.f90", 
"integrals/Auto2e/src/auto2e_eri_hfgf.f90", 
"integrals/Auto2e/src/auto2e_eri_hfgg.f90", 
"integrals/Auto2e/src/auto2e_eri_hfgp.f90", 
"integrals/Auto2e/src/auto2e_eri_hfgs.f90", 
"integrals/Auto2e/src/auto2e_eri_hfhd.f90", 
"integrals/Auto2e/src/auto2e_eri_hfhf.f90", 
"integrals/Auto2e/src/auto2e_eri_hfhp.f90", 
"integrals/Auto2e/src/auto2e_eri_hfhs.f90", 
"integrals/Auto2e/src/auto2e_eri_hfpp.f90", 
"integrals/Auto2e/src/auto2e_eri_hfps.f90", 
"integrals/Auto2e/src/auto2e_eri_hfss.f90", 
"integrals/Auto2e/src/auto2e_eri_hgdd.f90", 
"integrals/Auto2e/src/auto2e_eri_hgdp.f90", 
"integrals/Auto2e/src/auto2e_eri_hgds.f90", 
"integrals/Auto2e/src/auto2e_eri_hgfd.f90", 
"integrals/Auto2e/src/auto2e_eri_hgff.f90", 
"integrals/Auto2e/src/auto2e_eri_hgfp.f90", 
"integrals/Auto2e/src/auto2e_eri_hgfs.f90", 
"integrals/Auto2e/src/auto2e_eri_hggd.f90", 
"integrals/Auto2e/src/auto2e_eri_hggf.f90", 
"integrals/Auto2e/src/auto2e_eri_hggg.f90", 
"integrals/Auto2e/src/auto2e_eri_hggp.f90", 
"integrals/Auto2e/src/auto2e_eri_hggs.f90", 
"integrals/Auto2e/src/auto2e_eri_hghd.f90", 
"integrals/Auto2e/src/auto2e_eri_hghf.f90", 
"integrals/Auto2e/src/auto2e_eri_hghg.f90", 
"integrals/Auto2e/src/auto2e_eri_hghp.f90", 
"integrals/Auto2e/src/auto2e_eri_hghs.f90", 
"integrals/Auto2e/src/auto2e_eri_hgpp.f90", 
"integrals/Auto2e/src/auto2e_eri_hgps.f90", 
"integrals/Auto2e/src/auto2e_eri_hgss.f90", 
"integrals/Auto2e/src/auto2e_eri_hhdd.f90", 
"integrals/Auto2e/src/auto2e_eri_hhdp.f90", 
"integrals/Auto2e/src/auto2e_eri_hhds.f90", 
"integrals/Auto2e/src/auto2e_eri_hhfd.f90", 
"integrals/Auto2e/src/auto2e_eri_hhff.f90", 
"integrals/Auto2e/src/auto2e_eri_hhfp.f90", 
"integrals/Auto2e/src/auto2e_eri_hhfs.f90", 
"integrals/Auto2e/src/auto2e_eri_hhgd.f90", 
"integrals/Auto2e/src/auto2e_eri_hhgf.f90", 
"integrals/Auto2e/src/auto2e_eri_hhgg.f90", 
"integrals/Auto2e/src/auto2e_eri_hhgp.f90", 
"integrals/Auto2e/src/auto2e_eri_hhgs.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhd.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhf.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhg.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhh.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhp.f90", 
"integrals/Auto2e/src/auto2e_eri_hhhs.f90", 
"integrals/Auto2e/src/auto2e_eri_hhpp.f90", 
"integrals/Auto2e/src/auto2e_eri_hhps.f90", 
"integrals/Auto2e/src/auto2e_eri_hhss.f90", 
"integrals/Auto2e/src/auto2e_eri_hpdd.f90", 
"integrals/Auto2e/src/auto2e_eri_hpdp.f90", 
"integrals/Auto2e/src/auto2e_eri_hpds.f90", 
"integrals/Auto2e/src/auto2e_eri_hpfd.f90", 
"integrals/Auto2e/src/auto2e_eri_hpff.f90", 
"integrals/Auto2e/src/auto2e_eri_hpfp.f90", 
"integrals/Auto2e/src/auto2e_eri_hpfs.f90", 
"integrals/Auto2e/src/auto2e_eri_hpgd.f90", 
"integrals/Auto2e/src/auto2e_eri_hpgf.f90", 
"integrals/Auto2e/src/auto2e_eri_hpgg.f90", 
"integrals/Auto2e/src/auto2e_eri_hpgp.f90", 
"integrals/Auto2e/src/auto2e_eri_hpgs.f90", 
"integrals/Auto2e/src/auto2e_eri_hphp.f90", 
"integrals/Auto2e/src/auto2e_eri_hphs.f90", 
"integrals/Auto2e/src/auto2e_eri_hppp.f90", 
"integrals/Auto2e/src/auto2e_eri_hpps.f90", 
"integrals/Auto2e/src/auto2e_eri_hpss.f90", 
"integrals/Auto2e/src/auto2e_eri_hsdd.f90", 
"integrals/Auto2e/src/auto2e_eri_hsdp.f90", 
"integrals/Auto2e/src/auto2e_eri_hsds.f90", 
"integrals/Auto2e/src/auto2e_eri_hsfd.f90", 
"integrals/Auto2e/src/auto2e_eri_hsff.f90", 
"integrals/Auto2e/src/auto2e_eri_hsfp.f90", 
"integrals/Auto2e/src/auto2e_eri_hsfs.f90", 
"integrals/Auto2e/src/auto2e_eri_hsgd.f90", 
"integrals/Auto2e/src/auto2e_eri_hsgf.f90", 
"integrals/Auto2e/src/auto2e_eri_hsgg.f90", 
"integrals/Auto2e/src/auto2e_eri_hsgp.f90", 
"integrals/Auto2e/src/auto2e_eri_hsgs.f90", 
"integrals/Auto2e/src/auto2e_eri_hshs.f90", 
"integrals/Auto2e/src/auto2e_eri_hspp.f90", 
"integrals/Auto2e/src/auto2e_eri_hsps.f90", 
"integrals/Auto2e/src/auto2e_eri_hsss.f90", 
"integrals/Auto2e/src/auto2e_eri_pppp.f90", 
"integrals/Auto2e/src/auto2e_eri_ppps.f90", 
"integrals/Auto2e/src/auto2e_eri_ppss.f90", 
"integrals/Auto2e/src/auto2e_eri_psps.f90", 
"integrals/Auto2e/src/auto2e_eri_psss.f90", 
"integrals/Auto2e/src/auto2e_eri_ssss.f90"])]
FileList += [("DFT", ["integrals/Auto2e/src/auto2e.f90"])]
FileList += [("DFT", ["integrals/OverlapIntegrals.f90"])]
FileList += [("DFT", ["integrals/sphergto.f90"])]
FileList += [("DFT", ["integrals/basis_sets.f90"])]
FileList += [("DFT", ["integrals/ECP/PseudopotentialData.f90"])]

FileList += [("DFT", ["integrals/Cholesky/ParallelCholesky.f90",
                      "integrals/ECP/Pseudopotential.f90",
                      "integrals/OneElectronInts.f90",
                      "integrals/grid/GridFunctions.f90",
                      "integrals/Cholesky/TwoStepCholesky_Step1.f90",
                      "integrals/Cholesky/TwoStepCholesky_Step2.f90"])]
FileList += [("DFT", ["integrals/Cholesky/TwoStepCholesky.f90"])]
FileList += [("DFT", ["integrals/grid/BeckeGrid.f90"])]
FileList += [("DFT", ["integrals/ECP/SOPseudopotential.f90",
                      "integrals/THC/TensorHypercontraction.f90"])]
# ---------------------------------------------------
# End of two-electron integrals
# ---------------------------------------------------
FileList += [("DFT", ["rpa/quadratures.f90"])]
FileList += [("DFT", ["integrals/MultipoleExpansion.f90"])]
FileList += [("DFT", ["integrals/jengine.f90"])]
FileList += [("DFT", ["integrals/screen.f90"])]
FileList += [("DFT", ["integrals/MolproInterface.f90"])]

FileList += [("DFT", ["xc-models/modrzej2016_x_params.f90"])]
FileList += [("DFT", ["xc-models/modrzej2016_x_energy.f90"])]
FileList += [("DFT", ["xc-models/pbe_x_energy.f90",
                      "xc-models/pbe_c_energy.f90",
                      "xc-models/lda_x_energy.f90",
                      "xc-models/b88opt_x_energy.f90",
                      "xc-models/b88_x_energy.f90",
                      "xc-models/lyp_c_energy.f90",
                      "xc-models/modrzej2012_c_energy.f90",
                      "xc-models/mvs_x_energy.f90",
                      "xc-models/scan_x_energy.f90",
                      "xc-models/tpss_x_energy.f90",
                      "xc-models/pw86_x_energy.f90",
                      "xc-models/slater_x_potential.f90"])]
FileList += [("DFT", ["xc-models/hjs_x_energy.f90",
                      "xc-models/pbe_xc_auxiliary.f90",
                      "xc-models/tpss_c_energy.f90",
                      "xc-models/scan_c_energy.f90",
                      "xc-models/lda_c_energy.f90"])]
FileList += [("DFT", ["xc-models/modrzej2014_xc_energy.f90",
                 "xc-models/tpss_xc_auxiliary.f90"])]
FileList += [("DFT", ["xc-models/modrzej2016_c_energy.f90"])]
FileList += [("DFT", ["xc-models/modrzej2016_xc_auxiliary.f90",
                 "xc-models/modrzej2016_x_hole.f90"])]
FileList += [("DFT", ["xc-models/modrzej2016_xc_energy.f90",
                      "xc-models/pbe_xc_energy.f90",
                      "xc-models/tpss_xc_energy.f90",
                      "xc-models/b88opt_xc_energy.f90",
                      "xc-models/scan_xc_energy.f90",
                      "xc-models/b88_xc_energy.f90",
                      "xc-models/hjs_xc_energy.f90",
                      "xc-models/pw86_xc_energy.f90",
                      "xc-models/mvs_xc_energy.f90"])]

FileList += [("DFT", ["mfm/lsdpw92.f90",
                 "mfm/vs98exch.f90"])]
FileList += [("DFT", ["mfm/vs98corr.f90"])]
FileList += [("DFT", ["mfm/m05corr.f90",
                 "mfm/m05exch.f90",
                 "mfm/m06corr.f90",
                 "mfm/m06exch.f90",
                 "mfm/m08m11corr.f90",
                 "mfm/m08m11exch.f90"])]
FileList += [("DFT", ["mfm/mfm.f90"])]

FileList += [("DFT", ["misc/orbextension.f90",
                 "misc/gridfunc.f90",
                 "misc/cmpidx.f90",
                 "misc/cc_gparams.f90",
                 "misc/images.f90",
                 "misc/tiledmatrix.f90"])]
FileList += [("DFT", ["misc/threads.f90"])]
FileList += [("DFT", ["misc/report.f90"])]
FileList += [("DFT", ["misc/parser.f90"])]
FileList += [("DFT", ["misc/basis.f90",
                 "misc/symmetry.f90",
                 "misc/slater_parser.f90"])]
FileList += [("DFT", ["dft-dispersion/mbd_params.f90",
                 "dft-dispersion/dftd3par.f90"])]
FileList += [("DFT", ["dft-dispersion/dftd3.f90",
                      "dft-dispersion/mbd.f90"])]
FileList += [("DFT", ["scf/lda.f90",
                      "scf/gga.f90",
                      "scf/mgga.f90",
                      "scf/br89.f90",
                      "scf/rsbr89.f90",
                      "scf/scfutils.f90",
                      "scf/guess.f90",
                      "scf/cptxhole.f90",
                      "scf/hfcoul.f90",
                      "scf/hfexch.f90",
                      "scf/roks.f90",
                      "scf/arh.f90",
                      "scf/cmplx_arh.f90",
                      "scf/uks_arh.f90",
                      "scf/CABS.f90"])]
FileList += [("DFT", ["scf/AtomicDensities.f90"])]
FileList += [("DFT", ["scf/hirshfeld.f90"])]
FileList += [("DFT", ["xc-models/chai2013_x_asymp.f90"])]
FileList += [("DFT", ["scf/auxint.f90"])]
FileList += [("DFT", ["hamiltonian/Exchange.f90",
                      "hamiltonian/Coulomb.f90",
                      "hamiltonian/KohnShamGGA.f90",
                      "hamiltonian/KohnShamMGGA.f90",
                      "hamiltonian/CholeskyCoulomb.f90",
                      "hamiltonian/CholeskyExchange.f90",
                      "hamiltonian/THCFock.f90"])]
FileList += [("DFT", ["hamiltonian/Fock.f90",
                      "hamiltonian/KohnSham.f90",
                      "hamiltonian/CholeskyFock.f90"])]
FileList += [("DFT", ["scf/fock2el.f90",
                 "scf/voldata.f90",
                 "scf/xcfunc.f90"])]
FileList += [("DFT", ["scf/fbuild.f90"])]
FileList += [("DFT", ["scf/scf.f90"])]
FileList += [("DFT", ["scf/Slater.f90"])]
FileList += [("DFT", ["scf/SCFMatrices.f90"])]
FileList += [("DFT", ["scf/real_scf.f90"])]
FileList += [("DFT", ["scf/PostSCF.f90"])]
FileList += [("DFT", ["scf/cmplx_scf.f90"])]
FileList += [("DFT", ["tddft/rttddft.f90"])]
FileList += [("DFT", ["tddft/xckernel.f90"])]
FileList += [("DFT", ["tddft/lresp.f90"])]

FileList += [("DFT", ["rpa/GaussPRNG.f90",
                      "rpa/OptFreqQuad.f90",
                      "rpa/OptLaplaceQuad.f90",
                      "rpa/OrbDiffHist.f90"])]
FileList += [("DFT", ["rpa/rpa_core.f90",
                      "rpa/rpa_core_SpinUnres.f90",
                      "rpa/rpa_core_MO.f90",
                      "rpa/rpa_Orbitals.f90"])]
FileList += [("DFT", ["rpa/rpa_CC_Singles.f90",
                      "rpa/rpa_CC_Doubles.f90",
                      "rpa/rpa_CC_Exchange.f90",
                      "rpa/rpa_MeanField.f90",
                      "rpa/rpa_CCD_Corrections_Experimental.f90",
                      "rpa/rpa_CCS_Corrections.f90",
                      "rpa/rpa_PT_Terms.f90"])]
FileList += [("DFT", ["rpa/rpa_CCD_Corrections.f90"])]
FileList += [("DFT", ["rpa/rpa_CC_1RDM.f90"])]
FileList += [("DFT", ["rpa/rpa_CC.f90"])]
FileList += [("DFT", ["rpa/rpa_THC.f90"])]
FileList += [("DFT", ["rpa/rpa.f90"])]
FileList += [("DFT", ["rpa/rpa_driver.f90"])]
FileList += [("CC", ["misc/scf_symm_driver.f90",
                 "ccsd/common_sub.f90"])]
FileList += [("CC", ["ccsd/t1_transformed_int.f90",
                 "ccsd/davidson/davidson_main.f90",
                 "ccsd/ccsd_transformed_integrals.f90",
                 "ccsd/cc_diis.f90",
                 "ccsd/ccutils.f90"])]
FileList += [("CC", ["ccsd/automatic_t1_t2_amplitudes.f90",
                 "misc/motransf.f90"])]
FileList += [("CC", ["ccsd/cisd/cisd11.f90",
                 "ccsd/cisd/cisd02.f90",
 	             "ccsd/cisd/cisd20.f90",
                 "ccsd/cisd/cisd12.f90",
                 "ccsd/cisd/cisd21.f90",
                 "ccsd/cisd/cisd22.f90"])]
FileList += [("CC", ["ccsd/cisd/cisd_block_11_mod.f90",
                 "ccsd/cisd/cisd_block_12_mod.f90",
                 "ccsd/cisd/cisd_block_21_mod.f90",
                 "ccsd/cisd/cisd_block_02_mod.f90",
                 "ccsd/cisd/cisd_block_20_mod.f90",
                 "ccsd/cisd/cisd_block_22_mod_part1.f90",
                 "ccsd/cisd/cisd_block_22_mod_part2.f90",
                 "ccsd/cisd/cisd_block_22_mod_part3.f90",
                 "ccsd/cisd/cisd_block_22_mod_part4.f90",
                 "ccsd/cisd/cisd_block_22_mod_part5.f90",
                 "ccsd/cisd/cisd_block_11_mod_dav.f90",
                 "ccsd/cisd/cisd_block_12_mod_dav.f90",
                 "ccsd/cisd/cisd_block_21_mod_dav.f90",
                 "ccsd/cisd/cisd_block_02_mod_dav.f90",
                 "ccsd/cisd/cisd_block_20_mod_dav.f90",
                 "ccsd/cisd/cisd_block_22_mod_part1_dav.f90",
                 "ccsd/cisd/cisd_block_22_mod_part2_dav.f90",
                 "ccsd/cisd/cisd_block_22_mod_part3_dav.f90",
                 "ccsd/cisd/cisd_block_22_mod_part4_dav.f90",
                 "ccsd/cisd/cisd_block_22_mod_part5_dav.f90"])]
FileList += [("CC", ["ccsd/cisd/cisd_block_22_mod.f90",
                 "ccsd/cisd/cisd_block_22_mod_dav.f90"])]
FileList += [("CC", ["ccsd/cc3_intermediates.f90"])]
FileList += [("CC", ["ccsd/cc3_intermediates_for_21.f90",
                 "ccsd/ccsd_intermediates.f90"])]
FileList += [("CC", ["ccsd/eom_func_singlet/eom_ccsd_11_trans.f90",
                 "ccsd/eom_func_singlet/eom_ccsd_12_trans.f90",
                 "ccsd/eom_func_singlet/eom_ccsd_21_trans.f90",
                 "ccsd/eom_func_singlet/eom_ccsd_22_trans.f90",
                 "ccsd/eom_func_singlet/v0_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v1_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v2_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v3_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v4_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v5_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v6_eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/v0_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v1_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v2_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v3_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v4_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v5_eom_cc3_32_trans.f90",
                 "ccsd/eom_func_singlet/v6_eom_cc3_32_trans.f90"])]
FileList += [("CC", ["ccsd/eom_func_singlet/eom_cc3_21_trans.f90",
                 "ccsd/eom_func_singlet/eom_cc3_13_trans.f90",
                 "ccsd/eom_func_singlet/eom_cc3_23_trans.f90",
                 "ccsd/eom_func_singlet/eom_cc3_31_trans.f90",
                 "ccsd/eom_func_singlet/eom_cc3_32_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_11_triplet_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_12_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_12_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_21_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_21_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_22_tripletmm_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_22_tripletmp_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_22_tripletpm_trans.f90",
                 "ccsd/eom_func_triplet/eom_ccsd_22_tripletpp_trans.f90",
                 "ccsd/eom_func_triplet/v1_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v2_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v3_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v4_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v5_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v6_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v7_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v8_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v9_eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/v1_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v2_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v3_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v4_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v5_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v6_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v7_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v8_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v9_eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/v1_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v2_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v3_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v4_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v5_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v6_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v7_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v8_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/v9_eom_cc3_32_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_13_triplet_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_21_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_21_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_23_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_23_tripletm_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_31_triplet_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_32_tripletp_trans.f90",
                 "ccsd/eom_func_triplet/eom_cc3_32_tripletm_trans.f90"])]
FileList += [("CC", ["ccsd/ccjac_singlet/ccjac_block_11_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_12_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_13_dav_part1.f90",
                 "ccsd/ccjac_singlet/ccjac_block_13_dav_part2.f90",
                 "ccsd/ccjac_singlet/ccjac_block_21_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_21_cc3_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part1.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part2.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part3.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part4.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part5.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part6.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part7.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part8.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part9.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part10.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part11.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part12.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part13.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part14.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav_part15.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part1.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part2.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part3.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part4.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part5.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part6.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part7.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part8.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part9.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part10.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part11.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part12.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav_part13.f90",
                 "ccsd/ccjac_singlet/ccjac_block_31_dav_part1.f90",
                 "ccsd/ccjac_singlet/ccjac_block_31_dav_part2.f90",
                 "ccsd/ccjac_singlet/ccjac_block_31_dav_part3.f90",
                 "ccsd/ccjac_singlet/ccjac_block_31_dav_part4.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part1.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part2.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part3.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part4.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part5.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part6.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part7.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part8.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part9.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part10.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part11.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part12.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part13.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav_part14.f90",
                 "ccsd/ccjac_triplet/ccjac_block_11_triplet_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_12_tripletm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_12_tripletp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_21_tripletm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_21_tripletp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part7.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part8.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part9.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part10.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part11.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part12.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav_part13.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_13_triplet_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_13_triplet_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_21_cc3_tripletp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_21_cc3_tripletm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part7.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part8.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part9.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part10.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav_part11.f90",
                 "ccsd/ccjac_triplet/ccjac_block_31_triplet_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_31_triplet_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_31_triplet_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletp_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletp_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletp_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletp_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part1.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part2.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part3.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part4.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part5.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part6.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part7.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part8.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part9.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part10.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav_part11.f90",
                 "ccsd/ccjac_triplet/ccjac_block_33_triplet_dav.f90"])]
FileList += [("CC", ["ccsd/ccjac_singlet/ccjac_block_diag.f90",
                 "ccsd/ccjac_singlet/ccjac_block_13_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_31_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_32_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_33_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_33_dav_mem.f90",
                 "ccsd/ccjac_singlet/ccjac_block_23_dav.f90",
                 "ccsd/ccjac_singlet/ccjac_block_22_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletmp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_22_tripletpp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_13_triplet_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_23_tripletm_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_31_triplet_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletp_dav.f90",
                 "ccsd/ccjac_triplet/ccjac_block_32_tripletm_dav.f90"])]
FileList += [("CC", ["ccsd/guess_davidson.f90"])]
FileList += [("CC", ["ccsd/ci.f90"])]
FileList += [("CC", ["ccsd/eom_cc3_13_mem_noR.f90",
                 "ccsd/eom_cc3_23_mem_noR.f90",
                 "ccsd/eom_cc3_31_mem.f90",
                 "ccsd/eom_cc3_32_mem.f90",
                 "ccsd/eom_cc3_13_mem.f90",
                 "ccsd/eom_cc3_23_mem.f90",
                 "ccsd/eom_cc3_31_mem_noR.f90",
                 "ccsd/eom_cc3_32_mem_noR.f90"])]
FileList += [("CC", ["ccsd/jacobian_triplet.f90"])]
FileList += [("CC", ["ccsd/jacobian.f90"])]
FileList += [("CC", ["ccsd/jacobian_d_small.f90"])]
FileList += [("CC", ["ccsd/s_gen.f90"])]
FileList += [("CC", ["ccsd/v0_tmxi.f90",
                 "ccsd/v1_tmxi.f90",
                 "ccsd/v2_tmxi.f90",
                 "ccsd/v3_tmxi.f90",
                 "ccsd/v4_tmxi.f90",
                 "ccsd/v5_tmxi.f90",
                 "ccsd/v6_tmxi.f90",
                 "ccsd/tmxi.f90",
                 "ccsd/tmga.f90",
                 "ccsd/tmxi_ccsd.f90",
                 "ccsd/tmga_ccsd.f90"])]
FileList += [("CC", ["ccsd/eomccsdprop.f90",
                 "ccsd/eom_vectors.f90"])]
FileList += [("CC", ["ccsd/density_gr_exc_functions_int.f90",
"ccsd/density_gr_exc_functions.f90"])]
FileList += [("CC", ["ccsd/density_matrix_gr_exc.f90",
"ccsd/density_exc_exc_functions_so_left_pt0123.f90",
"ccsd/prop/ss_cc3_pt3a.f90",
"ccsd/prop/tt_ccsd_pt012a.f90",
"ccsd/prop/tt_ccsd_pt3a.f90",
"ccsd/prop/tt_ccsd_pt4a.f90",
"ccsd/prop/tt_cc3_pt012a.f90",
"ccsd/prop/tt_cc3_pt3a.f90",
"ccsd/prop/so_ccsd_pt4a.f90",
"ccsd/prop/so_cc3_pt3a.f90"])]
FileList += [("CC", ["ccsd/prop/ss_ccsd_pt012.f90",
"ccsd/prop/ss_ccsd_pt3.f90",
"ccsd/prop/ss_ccsd_pt4.f90",
"ccsd/prop/ss_cc3_pt012.f90",
"ccsd/prop/ss_cc3_pt3b.f90",
"ccsd/prop/ss_cc3_pt4.f90",
"ccsd/prop/tt_ccsd_pt012b.f90",
"ccsd/prop/tt_ccsd_pt3b.f90",
"ccsd/prop/tt_ccsd_pt4b.f90",
"ccsd/prop/tt_ccsd_pt4c.f90",
"ccsd/prop/tt_ccsd_pt4d.f90",
"ccsd/prop/tt_cc3_pt012b.f90",
"ccsd/prop/tt_cc3_pt3b.f90",
"ccsd/prop/tt_cc3_pt3c.f90",
"ccsd/prop/tt_cc3_pt4.f90",
"ccsd/prop/so_ccsd_pt012.f90",
"ccsd/prop/so_ccsd_pt3.f90",
"ccsd/prop/so_ccsd_pt4b.f90",
"ccsd/prop/so_cc3_pt012.f90",
"ccsd/prop/so_cc3_pt3b.f90",
"ccsd/prop/so_cc3_pt4.f90",
"ccsd/overlap_exc_exc_functions.f90",
"ccsd/density_matrix_ground.f90"])]
FileList += [("CC", ["ccsd/density_matrix_exc_exc.f90"])]
FileList += [("CC", ["ccsd/ccsd.f90"])]
FileList += [("DFT", ["misc/mp2.f90"])]
FileList += [("DFT", ["driver/initialize.f90"])]
FileList += [("CC", ["driver/drv_wm_intermediates_init.f90"])]

FileList += [("DFT", ["driver/drv_dft.f90",
                      "driver/drv_mp2.f90",
                      "driver/drv_dft_rpa.f90"])]
FileList += [("DFT", ["driver/drv_dft_disp.f90"])]
FileList += [("CC", ["driver/drv_cc_ground.f90",
                 "driver/drv_cc_aux.f90"])]
FileList += [("CC", ["driver/drv_cc_prop.f90"])]
FileList += [("DFT", ["driver/driver.f90"])]
#
# List of files preprocessed before compilation
#
PreprocessList = {}
PreprocessList["CC"] = ["driver/driver.f90"]


